# Site settings
name: PRAGMA Operations Center website
title: PRAGMA Operations Center
email: pragma-discussion@googlegroups.com

description: > # this means to ignore newlines until "baseurl:"
  PRAGMA Operations Center technical documentation

baseurl: "" # the subpath of your site, e.g. /blog/

# uncomment rul when have it and add CMAKE
#url: "http://goc.pragmagrid.net" # the base hostname & protocol for your site

#twitter_username: jekyllrb
github_username:  pragmagrid

# Build settings
markdown: kramdown

#permalink: /blog/:year/:month/:day/:title
permalink: /:title/

collections:
  resources:
      output: true
  projects:
     output: true
  people:
     output: true
  meetings:
     output: true


exclude:
  - README
  - Makefile
  - server.sh
  - junk/

